// Named shots for packs/sequences.json `props.shot` ids (GAPS.md "art to build"), built from shots/ over existing art.
// Each alias = { bg: shot component id, props }. `borrowed: true` = no real art for that place yet (see VISUAL-GAPS.md).
export const SHOT_ALIASES = {
  'feet-park': { bg: 'insert', props: { item: 'feet', pose: 'park', of: 'park', tone: 'day' } },
  'feet-wet': { bg: 'insert', props: { item: 'feet', pose: 'wet', of: 'crossing-night', tone: 'night' } },
  'bento-lid': { bg: 'insert', props: { item: 'bento', of: 'rooftop', caption: 'itadakimasu ♡' } },
  'nanda-watch': { bg: 'reaction', props: { emote: 'hearts', of: 'rooftop' } },
  'park-wide': { bg: 'establish', props: { of: 'street-day', from: [420, 420], to: [1500, 380], zoom: 1.4, tone: 'day' }, borrowed: true },
  'hands-lock': { bg: 'insert', props: { item: 'hands', of: 'street-day' } },
  'three-cups-basket': { bg: 'insert', props: { item: 'cups3', of: 'shop-street' } },
  'shop-exit': { bg: 'closeup', props: { of: 'shop-street', x: 1300, y: 560, zoom: 1.8, tone: 'day' } },
  'library-int': { bg: 'insert', props: { item: 'book', of: 'street-day', caption: 'shh… library' }, borrowed: true },
  'book-slot': { bg: 'insert', props: { item: 'book', of: 'street-day', caption: 'thunk.', tilt: 6 } },
  'crossing-bell': { bg: 'closeup', props: { of: 'rail-crossing', x: 760, y: 420, zoom: 2.2 } },
  'curry-house-int': { bg: 'closeup', props: { of: 'curry-house', x: 960, y: 540, zoom: 1 } },
  'curry-house-ext': { bg: 'closeup', props: { of: 'shop-street', x: 700, y: 520, zoom: 1.7, tone: 'day' }, borrowed: true },
  'dish-butter': { bg: 'insert', props: { item: 'butter-chicken', of: 'curry-house', tone: 'dusk' } },
  'dish-katsu': { bg: 'insert', props: { item: 'katsu', of: 'curry-house', tone: 'dusk' } },
  'nanda-eat-butter': { bg: 'reaction', props: { emote: 'hearts', of: 'curry-house' } },
  'nanda-eat-katsu': { bg: 'reaction', props: { emote: 'or', of: 'curry-house' } },
  'station-gate': { bg: 'establish', props: { of: 'naan', from: [500, 540], to: [1400, 540], zoom: 1.3 } },
  'ic-card-tap': { bg: 'insert', props: { item: 'ic-card', of: 'naan' } },
  'train-door': { bg: 'closeup', props: { of: 'train', x: 960, y: 500, zoom: 1.6 } },
  'umbrella-shoulder': { bg: 'insert', props: { item: 'umbrella', of: 'crossing-night', tone: 'night' } },
  'key-in-hand': { bg: 'insert', props: { item: 'key', of: 'street-dusk', tone: 'dusk' } },
  'kitchen-wide': { bg: 'establish', props: { of: 'teatable', from: [600, 540], to: [1300, 540], zoom: 1.3 }, borrowed: true },
  'tea-pour': { bg: 'insert', props: { item: 'teacup', of: 'teatable', tone: 'dusk' } },
  'hatch-dark': { bg: 'closeup', props: { of: 'basement', x: 960, y: 300, zoom: 2 } },
  'cups-end': { bg: 'insert', props: { item: 'cups-end', of: 'teatable', tone: 'night' } },
  'street-night-window': { bg: 'closeup', props: { of: 'street-dusk', x: 1100, y: 420, zoom: 1.5, tone: 'night' } },
  'cafe-cups': { bg: 'establish', props: { of: 'cafe', from: [500, 560], to: [1400, 560], zoom: 1.35 } },
};
