// Regenerates LOVE-AUDIT.md: node research/sprint-0930/alt-test/love-audit.mjs
// "old" = the graph without packs/love.json (what PR #27 shipped before the audit); "new" = the shipped graph.
import fs from 'node:fs';
import { applyPacks } from '../../../src/date-beta/packs/index.js';
import { loadScenes } from '../../../src/date-beta/engine.js';
import base from '../../../src/date-beta/scenes.json' with { type: 'json' };
import manifest from '../../../src/date-beta/assets.json' with { type: 'json' };
import { ART_NAMES } from '../../../src/date-beta-art-names.js';
import { FINAL } from '../../../src/date-beta-final.js';
import { choiceBeats } from '../../../src/date-beta-love-audit.js';
import story from '../../../src/date-beta/packs/story.json' with { type: 'json' };
import meta from '../../../src/date-beta/packs/meta.json' with { type: 'json' };
import mech from '../../../src/date-beta/packs/mech.json' with { type: 'json' };
import lockgame from '../../../src/date-beta/packs/lockgame.json' with { type: 'json' };
import obbp from '../../../src/date-beta/packs/obbp.json' with { type: 'json' };
import sequences from '../../../src/date-beta/packs/sequences.json' with { type: 'json' };
import v2 from '../../../src/date-beta/packs/variant-v2.json' with { type: 'json' };

const ROMANCE = ['street-day', 'street-dusk', 'shop-street', 'rail-crossing', 'crossing-day', 'crossing-night'];
const OLD = loadScenes(applyPacks(base, [story, meta, mech, lockgame, obbp, sequences, v2]), { manifest, art: [...ART_NAMES, ...ROMANCE, 'lock-game'] });
const oldAt = (id) => { const [s, i] = id.split(':'); return OLD.find((x) => x.id === s).beats[+i]; };
const sgn = (n) => (n > 0 ? `+${n}` : `${n}`);
const rows = choiceBeats(FINAL);
const oldOf = (x) => oldAt(x.id).choices.map((c) => c.love);

const out = [];
const P = (s = '') => out.push(s);
const changed = rows.filter((x) => oldOf(x).some((v, i) => v !== x.beat.choices[i].love));
const issues = rows.filter((x) => { const o = oldOf(x); return o.some((v) => !v) || new Set(o).size === 1; });

P('# Love audit (PR #27, sprint/obbp)');
P();
P('Tony: "does each multiple choice path (inconsequential one included) all affect points? if not do it."');
P();
P(`Audited every beat with 2+ options in the final applied scene graph (packs in play order, then \`packs/love.json\`): ${rows.length} choice beats, ${rows.filter((x) => x.live).length} reachable from scene 1 today (the rest are the old off-path scenes that stay in the data). Love goal ${FINAL.love.goal}.`);
P();
P(`Before: ${issues.length} beats had an option with no love value (0) or all options equal, all of them "move" picks (walk / open / climb / look). After: every option of every beat is non-zero and each beat has a positive and a negative option. Generated by \`research/sprint-0930/alt-test/love-audit.mjs\`; enforced by \`src/date-beta-loveaudit.test.js\`.`);
P();
P('Rule used for the moves: the plain wording is -1 (she did not like that), the cute / obsessive wording (the heart or "... and nothing else") is +1. A fake pick (`walk-home:7` "Run home alone") plays option 0 and takes its value, so it is -1 too. Patched in `packs/love.json` (runs last, so beat numbers are final), via a new pack patch form `{scene, beat, choice, set}`.');
P();
P('## Changed');
P();
P('| scene:beat | live | options | old | new |');
P('|---|---|---|---|---|');
for (const x of changed) P(`| ${x.id} | ${x.live ? 'yes' : 'off-path'} | ${x.beat.choices.map((c) => c.text.replace(/\|/g, '/')).join(' / ')} | ${oldOf(x).map(sgn).join(' / ')} | ${x.beat.choices.map((c) => sgn(c.love)).join(' / ')} |`);
P();
P('## Already fine (unchanged)');
P();
P('| scene:beat | live | options | love |');
P('|---|---|---|---|');
for (const x of rows.filter((y) => !changed.includes(y))) P(`| ${x.id} | ${x.live ? 'yes' : 'off-path'} | ${x.beat.choices.map((c) => c.text.replace(/\|/g, '/')).join(' / ')} | ${x.beat.choices.map((c) => sgn(c.love)).join(' / ')} |`);
P();
fs.writeFileSync(new URL('./LOVE-AUDIT.md', import.meta.url), out.join('\n') + '\n');
console.log(`${rows.length} beats, ${changed.length} changed`);
