// V1 Shinkai: light, sky, weather, restraint. The sky tells the time. Few words; holds do the feeling.
const errandGo = [{ if: { errand: 'groceries' }, to: 'shop' }, { to: 'library' }];
export default {
  title: 'V1 Shinkai (light / sky / restraint)',
  roofHead: { head: 'rooftop (existing bento + taste picks kept; one stamp added after the goal card)' },
  roofStamp: { shot: 'establishing sky → stamp', id: 'stamp', stamp: ['SCHOOL ROOFTOP', '12:00 NOON'], text: 'SCHOOL ROOFTOP · 12:00 NOON. Blue sky. One cloud. Rain is coming later.', cue: 'wind', sfx: 'wind bed' },
  path: ['park', ['shop', 'library'], 'curry', 'train', 'rain', 'street', 'home'],
  scenes: [
    { id: 'park', title: 'V1 park', short: 'PARK', bg: 'park', head: 'PARK · 1:00 PM (decisions: hand, errand)',
      why: 'She is nervous (will you hold her hand?), then calm once your hand is locked in hers.',
      beats: [
        { shot: 'establishing pan (sky → trees)', id: 'establish', stamp: ['PARK', '1:00 PM'], text: 'PARK · 1:00 PM. Cherry trees. Blue sky. Petals fall slowly.', cue: 'wind', sfx: 'birdsong + wind bed' },
        { shot: 'medium, backlit (lens flare)', id: 'park-wide', spk: 'N', text: 'Hold my hand. Hands get lost if you let go.', cue: 'breath', sfx: 'breath',
          pick: [['Hold it tight', 3, 'hearts', 'Tight. Good. Now you cannot drift away.'], ['Hold one finger', 1, 'sweat', 'One finger today. All five later.'], ['Pull your hand back', -4, 'hate', 'Okay. Your hand is cold anyway.']] },
        { shot: 'insert (hands)', id: 'hands-lock', text: 'Close-up. Her fingers lock between yours. Tight.', cue: 'thump', sfx: 'fabric + thump' },
        { shot: 'hold / ma (empty sky)', id: 'establish', props: { tone: 'day' }, text: 'Silence. Wind moves the petals. She does not let go.', cue: 'silence', sfx: 'SILENCE 2 s', emo: 'petals stop 1 frame' },
        { shot: 'two-shot', id: 'ots', spk: 'N', text: 'One job before lunch. My groceries, or my library book?',
          pick: [['Carry her groceries', 2, 'heart', 'Groceries. For our dinner.', { errand: 'groceries' }], ['Return her book', 2, 'heart', 'The book. It is very late.', { errand: 'library' }], ['Do it alone, later', -4, 'hate', 'Alone? No. Groceries. Now.', { errand: 'groceries' }]] },
        { shot: 'pull-out (exit, loneliness)', id: 'push', props: { to: 0.8 }, text: 'Pull out. Two small people leave the park. The petals cover the path.', cue: 'wind', sfx: 'wind', move: ['Walk with her', errandGo] },
      ] },
    { id: 'shop', title: 'V1 shop street', short: 'SHOP', bg: 'shop-street', head: 'SHOP STREET · 2:00 PM (errand: groceries)',
      why: 'She is happy and busy. She gets calm and pleased when your hands are full and cannot leave.',
      beats: [
        { shot: 'establishing (roofs, sky)', id: 'establish', stamp: ['SHOP STREET', '2:00 PM'], text: 'SHOP STREET · 2:00 PM. Small shops. Pink petals on the roofs.', cue: 'wind', sfx: 'street murmur bed' },
        { shot: 'medium', id: 'shop-street', spk: 'N', text: 'Carrots. Rice. And three cups. We need three cups.' },
        { shot: 'insert (basket)', id: 'three-cups-basket', text: 'Close-up. Three cups in the basket. She touches the third one.', cue: 'thump', sfx: 'cups clink' },
        { shot: 'reaction (you), hold', id: 'reaction', props: { emote: 'sweat' }, text: 'You count. There are two of you. She bought three cups.', cue: 'silence', sfx: 'SILENCE' },
        { shot: 'medium', id: 'shop-exit', spk: 'N', text: 'You carry the bags. Now your hands are full. Good.', emo: 'smile' },
        { shot: 'cut on action (door)', id: 'shop-exit', text: 'The shop bell rings. The bags pull on your fingers.', cue: 'bell', sfx: 'door bell', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'library', title: 'V1 library', short: 'BOOK', bg: 'rail-crossing', head: 'RAIL CROSSING → LIBRARY · 1:50–2:00 PM (errand: book)',
      why: 'She is tense at the train gate (a train is a door that takes people). She relaxes when the book is gone.',
      beats: [
        { shot: 'establishing + stamp', id: 'stamp', stamp: ['RAIL CROSSING', '1:50 PM'], text: 'RAIL CROSSING · 1:50 PM. The bell rings. The gate is down.', cue: 'bell', sfx: 'crossing bell kan-kan' },
        { shot: 'close-up (her face, train blur behind)', id: 'crossing-bell', spk: 'N', text: 'A train is a big metal door. I hate doors. Stand closer.', cue: 'train-hum', sfx: 'train passes' },
        { shot: 'establishing (cool light)', id: 'library-int', stamp: ['LIBRARY', '2:00 PM'], text: 'LIBRARY · 2:00 PM. Cool air. Very quiet. Light on the floor.', cue: 'silence', sfx: 'room tone' },
        { shot: 'insert (book slot)', id: 'book-slot', text: 'Close-up. She drops the book in the return slot. Thunk.', cue: 'thump', sfx: 'book thunk' },
        { shot: 'medium', id: 'library-int', spk: 'N', text: 'The book was forty days late. You touched it once. So I kept it.' },
        { shot: 'exit (doors, hot sun)', id: 'establish', text: 'The library doors close. Cold air behind you. Hot sun in front.', cue: 'wind', sfx: 'door hush', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'curry', title: 'V1 curry house', short: 'CURRY', bg: 'cafe', head: 'CURRY HOUSE · 3:00 PM (decision: lunch)',
      why: 'She is hungry and demanding, then soft and happy because you fed her.',
      beats: [
        { shot: 'establishing (warm window light)', id: 'curry-house-int', stamp: ['CURRY HOUSE', '3:00 PM'], text: 'CURRY HOUSE · 3:00 PM. Small and warm. Two seats, side by side.', cue: 'kettle', sfx: 'restaurant bed + sizzle' },
        { shot: 'medium', id: 'curry-house-int', spk: 'N', text: 'I am hungry. You pick my lunch. Pick the right one.',
          pick: [['Butter chicken for her', 3, 'hearts', 'With naan! You know me.', { food: 'butter' }], ['Katsu curry', 2, 'heart', 'Crunchy. Good choice.', { food: 'katsu' }], ['I am not hungry', -4, 'hate', 'Then you watch me eat.', { food: 'katsu' }]] },
        { shot: 'insert (dish, steam in the light)', id: 'insert', text: 'dish', cue: 'thump', sfx: 'plate down',
          vary: { food: { butter: { text: 'Close-up. Butter chicken. Orange sauce. Steam rises from the naan.', props: { shot: 'dish-butter' } }, katsu: { text: 'Close-up. Katsu curry. The knife cuts the pork. Crunch.', props: { shot: 'dish-katsu' } } } } },
        { shot: 'two-shot', id: 'ots', spk: 'N', text: 'feed', vary: { food: { butter: { text: 'Tear the naan. Feed me the soft part. Then I feed you.' }, katsu: { text: 'Cut me a piece. Blow on it. Then feed me.' } } } },
        { shot: 'reaction (her, eating)', id: 'reaction', props: { emote: 'hearts' }, text: 'She eats. She looks at you, not at the food.', cue: 'breath', sfx: 'chewing, then quiet', emo: 'hearts' },
        { shot: 'exit (window light turns gold)', id: 'curry-house-ext', text: 'The window light turns gold. The door bell rings. You leave.', cue: 'bell', sfx: 'door bell', move: ['Walk to the station', 'train'] },
      ] },
    { id: 'train', title: 'V1 station and train', short: 'TRAIN', bg: 'train', head: 'STATION → TRAIN · 4:30–5:20 PM (loop line changes by run)',
      why: 'She is proud of her plan. On run 2 and 3 she is openly pleased that you forgot.',
      beats: [
        { shot: 'establishing (glass roof, light shafts)', id: 'station-gate', stamp: ['STATION', '4:30 PM'], text: 'STATION · 4:30 PM. Light comes through the glass roof.', cue: 'train-hum', sfx: 'station bed' },
        { shot: 'insert (IC card)', id: 'ic-card-tap', text: 'Close-up. She taps her card. Then she taps it again, for you.', cue: 'tick', sfx: 'card beep x2' },
        { shot: 'medium (seat, window behind)', id: 'train', spk: 'N', text: 'loop', vary: { run: { 1: { text: 'Twelve stops to my home. I counted them this morning.' }, 2: { text: 'Twelve stops. We did this before. You forgot. I did not.' }, 3: { text: 'Third time today. Same train. Same seat. Same you.' } } } },
        { shot: 'time-lapse sky (window)', id: 'timelapse', props: { of: 'train', tones: ['day', 'dusk', 'night'] }, stamp: ['TRAIN', '4:40 → 5:20 PM'], text: 'Out the window, the sky goes orange, then grey. Rain starts.', cue: 'rain', sfx: 'rail clack, rain on glass' },
        { shot: 'exit (doors open)', id: 'train-door', text: 'Her stop. The doors open. Cold, wet air comes in.', cue: 'bell', sfx: 'door chime + hiss', move: ['Step off the train', 'rain'] },
      ] },
    { id: 'rain', title: 'V1 rain crossing', short: 'RAIN', bg: 'crossing-night', head: 'BIG CROSSING · 5:30 PM, rain (decision: umbrella)',
      why: 'She is cold and wet, and happy anyway, because the umbrella keeps you close.',
      beats: [
        { shot: 'establishing (neon in puddles)', id: 'establish', stamp: ['BIG CROSSING', '5:30 PM'], text: 'BIG CROSSING · 5:30 PM. Heavy rain. The signs glow. Nobody else.', cue: 'rain', sfx: 'rain bed' },
        { shot: 'two-shot under umbrella', id: 'crossing-night', spk: 'N', text: 'Share my umbrella. It is small. We have to stand close.',
          pick: [['Step under, close', 4, 'hearts', 'Good. Now the rain cannot take you.'], ['Hold it for her', 1, 'sweat', 'Tall and useful. I am keeping you.'], ['I will just get wet', -4, 'hate', 'Then get wet. Sick boys stay inside.']] },
        { shot: 'insert (wet shoulder)', id: 'umbrella-shoulder', text: 'Close-up. Her shoulder is wet. Yours is dry.', cue: 'rain', sfx: 'rain on umbrella' },
        { shot: 'hold / ma', id: 'crossing-night', text: 'She says nothing for three seconds. Only rain.', cue: 'silence', sfx: 'SILENCE (rain drops out)' },
        { shot: 'exit: sky opens (light break)', id: 'timelapse', props: { of: 'crossing-night', tones: ['night', 'dusk'] }, text: 'The rain stops. The clouds open. Orange light on the wet road.', cue: 'wind', sfx: 'drips', move: ['Walk her home', 'street'] },
      ] },
    { id: 'street', title: 'V1 her street', short: 'STREET', bg: 'street-day', head: 'HER STREET · 6:00 → 7:00 PM (decision: pace)',
      why: 'She is afraid the day will end. She calms when the lights come on, because now you are at her door.',
      beats: [
        { shot: 'establishing (low sun, long shadows)', id: 'establish', stamp: ['HER STREET', '6:00 PM'], text: 'HER STREET · 6:00 PM. Wet road. Low sun. She walks slower.', cue: 'wind', sfx: 'cicadas + footsteps' },
        { shot: 'medium (her back to the sun)', id: 'street-day', spk: 'N', text: 'If we walk slowly, the day cannot end.',
          pick: [['Walk slower with her', 3, 'hearts', 'Slower. Slower. There. We are almost still.'], ['Keep the same pace', 1, 'sweat', 'Same pace. Same day. Same you.'], ['I need to go home', -5, 'hate', 'Home? You are walking me home.']] },
        { shot: 'time-lapse sky (the one big Shinkai shot)', id: 'timelapse', props: { of: 'street-dusk', tones: ['day', 'dusk', 'night'] }, stamp: ['HER STREET', '6:00 → 7:00 PM'], text: 'The sky goes orange, then pink, then dark blue. One hour passes.', cue: 'silence', sfx: 'SILENCE, then crickets' },
        { shot: 'insert (key)', id: 'key-in-hand', text: 'Close-up. Her house key. It is warm. She held it all day.', cue: 'tick', sfx: 'keys' },
        { shot: 'close-up', id: 'closeup', spk: 'N', text: 'I held it since noon. So I would be ready. For you.' },
        { shot: 'exit (streetlights on, one by one)', id: 'street-dusk', text: 'The streetlights turn on, one by one. Her door. Unit 12.', cue: 'tick', sfx: 'light hum x3', move: ['Follow her inside', 'home'] },
      ] },
    { id: 'home', title: 'V1 her home', short: 'HOME', bg: 'genkan-in', head: 'HER DOOR → KITCHEN · 7:05–7:10 PM',
      why: 'She stops pretending to be a guest on a date. She is at home now, calm and in charge.',
      beats: [
        { shot: 'establishing + stamp (warm light)', id: 'stamp', stamp: ['HER HOME', '7:05 PM'], text: 'HER HOME · 7:05 PM. Men\'s slippers by the door. Your size.', cue: 'silence', sfx: 'door shuts, room tone' },
        { shot: 'medium', id: 'genkan-in', spk: 'N', text: 'Every road today came here. I planned all of them.', emo: 'smile, no blink' },
        { shot: 'establishing (kitchen)', id: 'kitchen-wide', bg: 'BG-D2', stamp: ['HER KITCHEN', '7:10 PM'], text: 'HER KITCHEN · 7:10 PM. Very clean. Three chairs. The kettle is warm.', cue: 'kettle', sfx: 'kettle click' },
        { shot: 'insert (pour, steam in lamp light)', id: 'tea-pour', text: 'Close-up. She pours tea into three cups.', cue: 'kettle', sfx: 'pour' },
        { shot: 'exit → sit (cut on action)', id: 'kitchen-wide', text: 'She pulls out a chair for you. The middle one.', cue: 'thump', sfx: 'chair scrape', move: ['Sit down', '!cup'] },
      ] },
  ],
};
