// V2 Yamada: hands, feet, glances. Close small sounds. Faces come late; the body tells the mood first.
const errandGo = [{ if: { errand: 'groceries' }, to: 'shop' }, { to: 'library' }];
export default {
  title: 'V2 Yamada (hands / feet / glances)',
  roofHead: { head: 'rooftop (existing bento + taste picks kept; one stamp added after the goal card)' },
  roofStamp: { shot: 'insert (her feet by the fence) + stamp', id: 'stamp', stamp: ['SCHOOL ROOFTOP', '12:00 NOON'], text: 'SCHOOL ROOFTOP · 12:00 NOON. Her shoes by the fence. Toes pointed at you.', cue: 'wind', sfx: 'wind bed' },
  path: ['park', ['shop', 'library'], 'curry', 'train', 'rain', 'street', 'home'],
  scenes: [
    { id: 'park', title: 'V2 park', short: 'PARK', bg: 'park', head: 'PARK · 1:00 PM (decisions: hand, errand)',
      why: 'Her hand shakes while she waits for yours. It goes still once she holds you: she got what she wanted.',
      beats: [
        { shot: 'establishing (path, petals) + stamp', id: 'establish', stamp: ['PARK', '1:00 PM'], text: 'PARK · 1:00 PM. A path under cherry trees. Petals on the ground.', cue: 'wind', sfx: 'birdsong + wind bed' },
        { shot: 'insert (feet walking)', id: 'closeup', props: { of: 'park', y: 900, zoom: 2 }, text: 'Close-up. Her feet. Two small steps for each of yours.', cue: 'tick', sfx: 'footsteps on gravel' },
        { shot: 'insert (her open hand, shaking)', id: 'hands-lock', spk: 'N', text: 'Hold my hand. My hand is shaking. Only yours can stop it.', cue: 'breath', sfx: 'breath',
          pick: [['Hold it tight', 3, 'hearts', 'It stopped. See? It only needed you.'], ['Hold one finger', 1, 'sweat', 'One finger. I will hold it very hard.'], ['Pull your hand back', -4, 'hate', 'Okay. My hand can wait. It is good at waiting.']] },
        { shot: 'extreme close-up (her thumb on your wrist)', id: 'closeup', props: { of: 'park', zoom: 3 }, text: 'Her thumb is on your wrist. She is counting your pulse.', cue: 'silence', sfx: 'SILENCE, one heartbeat' },
        { shot: 'glance (rack focus: hands → her eyes)', id: 'rack', props: { focus: 'her', emote: 'heart' }, spk: 'N', text: 'One job before lunch. My groceries, or my library book?',
          pick: [['Carry her groceries', 2, 'heart', 'Groceries. For our dinner.', { errand: 'groceries' }], ['Return her book', 2, 'heart', 'The book. It is very late.', { errand: 'library' }], ['Do it alone, later', -4, 'hate', 'Alone? No. Groceries. Now.', { errand: 'groceries' }]] },
        { shot: 'exit (two pairs of feet leave frame)', id: 'closeup', props: { of: 'park', y: 900, zoom: 2 }, text: 'Two pairs of shoes walk out of the park. Hers stay close to yours.', cue: 'tick', sfx: 'footsteps fade', move: ['Walk with her', errandGo] },
      ] },
    { id: 'shop', title: 'V2 shop street', short: 'SHOP', bg: 'shop-street', head: 'SHOP STREET · 2:00 PM (errand: groceries)',
      why: 'She is bright with the shop lady, then cold, because the shop lady smiled at you.',
      beats: [
        { shot: 'establishing + stamp', id: 'establish', stamp: ['SHOP STREET', '2:00 PM'], text: 'SHOP STREET · 2:00 PM. Small shops. People buy food for dinner.', cue: 'wind', sfx: 'street murmur bed' },
        { shot: 'insert (her hand picks cups)', id: 'three-cups-basket', text: 'Close-up. Her hand puts one cup in the basket. Then two. Then three.', cue: 'thump', sfx: 'cup clink x3' },
        { shot: 'over-the-shoulder (the shop lady)', id: 'ots', props: { emote: 'pout' }, text: 'The shop lady smiles at you. Nanda sees it.', cue: 'silence', sfx: 'SILENCE' },
        { shot: 'insert (her nails in the basket handle)', id: 'closeup', props: { of: 'shop-street', zoom: 3 }, text: 'Close-up. Her nails press into the basket handle. Hard.', cue: 'thump', sfx: 'wicker creak' },
        { shot: 'close-up (her smile comes back)', id: 'closeup', spk: 'N', text: 'Do not look at her. Look at me. I bought you a cup.' },
        { shot: 'exit (bags in your hands)', id: 'shop-exit', text: 'The shop bell rings. You carry the bags. She holds your sleeve.', cue: 'bell', sfx: 'door bell', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'library', title: 'V2 library', short: 'BOOK', bg: 'rail-crossing', head: 'RAIL CROSSING → LIBRARY · 1:50–2:00 PM (errand: book)',
      why: 'She holds the book like a pet. She is sad to give it back, then happy: now only she has your touch on it.',
      beats: [
        { shot: 'establishing + stamp', id: 'stamp', stamp: ['RAIL CROSSING', '1:50 PM'], text: 'RAIL CROSSING · 1:50 PM. The bell rings. The gate is down.', cue: 'bell', sfx: 'crossing bell kan-kan' },
        { shot: 'insert (her hand grips your sleeve)', id: 'crossing-bell', text: 'A train passes. Her hand grabs your sleeve until it is gone.', cue: 'train-hum', sfx: 'train roar' },
        { shot: 'establishing + stamp', id: 'library-int', stamp: ['LIBRARY', '2:00 PM'], text: 'LIBRARY · 2:00 PM. Cool air. Very quiet.', cue: 'silence', sfx: 'room tone' },
        { shot: 'insert (her fingers on the book cover)', id: 'book-slot', spk: 'N', text: 'You touched this book once. Right here. I kept it forty days.' },
        { shot: 'insert (book slot)', id: 'book-slot', text: 'Close-up. The book drops into the slot. Thunk.', cue: 'thump', sfx: 'book thunk' },
        { shot: 'exit (her empty hand finds yours)', id: 'hands-lock', text: 'Her empty hand finds your hand. You walk out.', cue: 'wind', sfx: 'door hush', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'curry', title: 'V2 curry house', short: 'CURRY', bg: 'cafe', head: 'CURRY HOUSE · 3:00 PM (decision: lunch)',
      why: 'She is hungry and bossy, then soft: you fed her with your own hand.',
      beats: [
        { shot: 'establishing + stamp', id: 'curry-house-int', stamp: ['CURRY HOUSE', '3:00 PM'], text: 'CURRY HOUSE · 3:00 PM. Two seats, side by side. Her knee touches yours.', cue: 'kettle', sfx: 'restaurant bed + sizzle' },
        { shot: 'medium', id: 'curry-house-int', spk: 'N', text: 'I am hungry. You pick my lunch. Pick the right one.',
          pick: [['Butter chicken for her', 3, 'hearts', 'With naan! You know me.', { food: 'butter' }], ['Katsu curry', 2, 'heart', 'Crunchy. Good choice.', { food: 'katsu' }], ['I am not hungry', -4, 'hate', 'Then you watch me eat.', { food: 'katsu' }]] },
        { shot: 'insert (dish)', id: 'insert', text: 'dish', cue: 'thump', sfx: 'plate down',
          vary: { food: { butter: { text: 'Close-up. Butter chicken. She tears the naan with two fingers.', props: { shot: 'dish-butter' } }, katsu: { text: 'Close-up. Katsu curry. She cuts one small piece. Crunch.', props: { shot: 'dish-katsu' } } } } },
        { shot: 'insert (your hand holds the spoon to her mouth)', id: 'closeup', props: { of: 'cafe', zoom: 2.5 }, spk: 'N', text: 'Feed me. With your hand. Not the spoon. Your hand.', cue: 'breath', sfx: 'breath' },
        { shot: 'extreme close-up (her lips, your fingers)', id: 'closeup', props: { of: 'cafe', zoom: 3 }, text: 'She eats from your fingers. Her eyes never leave your face.', cue: 'silence', sfx: 'SILENCE', emo: 'hearts' },
        { shot: 'exit (her napkin wipes your hand, door)', id: 'curry-house-ext', text: 'She wipes your fingers with her napkin. Then she keeps the napkin.', cue: 'bell', sfx: 'door bell', move: ['Walk to the station', 'train'] },
      ] },
    { id: 'train', title: 'V2 station and train', short: 'TRAIN', bg: 'train', head: 'STATION → TRAIN · 4:30–5:20 PM (loop line changes by run)',
      why: 'She is calm and pleased. On runs 2 and 3 she shows you she remembers, with her fingers.',
      beats: [
        { shot: 'establishing + stamp', id: 'station-gate', stamp: ['STATION', '4:30 PM'], text: 'STATION · 4:30 PM. Many feet walk past. Hers stop next to yours.', cue: 'train-hum', sfx: 'station bed' },
        { shot: 'insert (IC card)', id: 'ic-card-tap', text: 'Close-up. She taps her card. Then she taps it again, for you.', cue: 'tick', sfx: 'card beep x2' },
        { shot: 'insert (her fingers count on her knee)', id: 'closeup', props: { of: 'train', zoom: 2.5 }, spk: 'N', text: 'loop', vary: { run: { 1: { text: 'Twelve stops. I count them on my fingers. See?' }, 2: { text: 'Twelve stops. Two days. I count those too. You forgot.' }, 3: { text: 'Three fingers. Three times today. Same train. Same you.' } } } },
        { shot: 'two-shot (her head on your shoulder, window)', id: 'train', stamp: ['TRAIN', '5:20 PM'], text: '5:20 PM. Her head is on your shoulder. Rain hits the window.', cue: 'rain', sfx: 'rail clack, rain on glass' },
        { shot: 'exit (her hand pulls your sleeve out the door)', id: 'train-door', text: 'Her stop. The doors open. She pulls you out by the sleeve.', cue: 'bell', sfx: 'door chime + hiss', move: ['Step off the train', 'rain'] },
      ] },
    { id: 'rain', title: 'V2 rain crossing', short: 'RAIN', bg: 'crossing-night', head: 'BIG CROSSING · 5:30 PM, rain (decision: umbrella)',
      why: 'She shivers, then smiles, because your arm touches hers under the small umbrella.',
      beats: [
        { shot: 'establishing + stamp', id: 'establish', stamp: ['BIG CROSSING', '5:30 PM'], text: 'BIG CROSSING · 5:30 PM. Heavy rain. The signs glow. Nobody else.', cue: 'rain', sfx: 'rain bed' },
        { shot: 'insert (her hand opens the umbrella)', id: 'umbrella-shoulder', spk: 'N', text: 'Share my umbrella. It is small. Our arms have to touch.',
          pick: [['Step under, close', 4, 'hearts', 'Our arms touch. Now I am warm.'], ['Hold it for her', 1, 'sweat', 'Your hand on the handle. My hand on yours.'], ['I will just get wet', -4, 'hate', 'Then get wet. Sick boys stay inside.']] },
        { shot: 'insert (her wet shoe, your dry shoe)', id: 'closeup', props: { of: 'crossing-night', y: 900, zoom: 2.2 }, text: 'Close-up. Her shoes are wet. She walks in the puddles for you.', cue: 'rain', sfx: 'splash' },
        { shot: 'glance (she looks up, you look away)', id: 'rack', props: { focus: 'her', emote: 'heart' }, text: 'She looks up at you. Then down. Then up again.', cue: 'silence', sfx: 'SILENCE (rain drops out)' },
        { shot: 'exit (feet walk out of the rain)', id: 'crossing-night', text: 'The rain stops. Two pairs of wet shoes walk toward her street.', cue: 'wind', sfx: 'drips', move: ['Walk her home', 'street'] },
      ] },
    { id: 'street', title: 'V2 her street', short: 'STREET', bg: 'street-day', head: 'HER STREET · 6:00 → 7:00 PM (decision: pace)',
      why: 'Her steps get smaller because she does not want the day to end. She stops being scared once she holds the key.',
      beats: [
        { shot: 'establishing + stamp', id: 'establish', stamp: ['HER STREET', '6:00 PM'], text: 'HER STREET · 6:00 PM. Wet road. Low sun. Long shadows.', cue: 'wind', sfx: 'cicadas + footsteps' },
        { shot: 'insert (her steps get smaller)', id: 'closeup', props: { of: 'street-day', y: 900, zoom: 2 }, spk: 'N', text: 'Take small steps. Small steps make the day longer.',
          pick: [['Walk slower with her', 3, 'hearts', 'Smaller. Smaller. There. We are almost still.'], ['Keep the same pace', 1, 'sweat', 'Same pace. Same day. Same you.'], ['I need to go home', -5, 'hate', 'Home? You are walking me home.']] },
        { shot: 'time cut + stamp (same feet, dusk)', id: 'stamp', bg: 'street-dusk', stamp: ['HER STREET', '7:00 PM'], text: '7:00 PM. The same street, now dark blue. You walked one hour.', cue: 'silence', sfx: 'SILENCE, then crickets' },
        { shot: 'insert (key in her fist)', id: 'key-in-hand', text: 'Close-up. Her house key. Her fist opens. Red marks on her palm.', cue: 'tick', sfx: 'keys' },
        { shot: 'close-up (her face, first time)', id: 'closeup', bg: 'street-dusk', spk: 'N', text: 'I held it since noon. So I would be ready. For you.' },
        { shot: 'exit (key turns in lock)', id: 'closeup', bg: 'street-dusk', props: { zoom: 3 }, text: 'Close-up. The key turns. Click. Door 12 opens.', cue: 'thump', sfx: 'lock click', move: ['Follow her inside', 'home'] },
      ] },
    { id: 'home', title: 'V2 her home', short: 'HOME', bg: 'genkan-in', head: 'HER DOOR → KITCHEN · 7:05–7:10 PM',
      why: 'She is calm and in charge now. She kneels to put slippers on your feet.',
      beats: [
        { shot: 'establishing + stamp', id: 'stamp', stamp: ['HER HOME', '7:05 PM'], text: 'HER HOME · 7:05 PM. Very clean. Her shoes in a perfect line.', cue: 'silence', sfx: 'door shuts, room tone' },
        { shot: 'insert (she puts slippers on your feet)', id: 'closeup', props: { of: 'genkan-in', y: 900, zoom: 2 }, text: 'She kneels. She puts slippers on your feet. Your size.', cue: 'thump', sfx: 'slipper pat' },
        { shot: 'close-up (looking up at you)', id: 'closeup', spk: 'N', text: 'Every road today came here. I planned all of them.', emo: 'smile, no blink' },
        { shot: 'establishing + stamp (kitchen)', id: 'kitchen-wide', bg: 'BG-D2', stamp: ['HER KITCHEN', '7:10 PM'], text: 'HER KITCHEN · 7:10 PM. Three chairs. Three cups. Steam.', cue: 'kettle', sfx: 'kettle click, pour' },
        { shot: 'exit (her hand on your back, you sit)', id: 'tea-pour', text: 'Her hand on your back. She sits you in the middle chair.', cue: 'thump', sfx: 'chair scrape', move: ['Sit down', '!cup'] },
      ] },
  ],
};
