// V3 Kon: match cuts (a shape carries us to the next place) + ONE reality slip at the rain crossing.
// Paprika rule: the cut flows, never confuses. The very next beat always stamps the new place and time.
const errandGo = [{ if: { errand: 'groceries' }, to: 'shop' }, { to: 'library' }];
export default {
  title: 'V3 Kon (match cuts / reality slip)',
  roofHead: { head: 'rooftop (existing bento + taste picks kept; one stamp added after the goal card)' },
  roofStamp: { shot: 'stamp (round bento lid echoes the round sun)', id: 'stamp', stamp: ['SCHOOL ROOFTOP', '12:00 NOON'], text: 'SCHOOL ROOFTOP · 12:00 NOON. A round sun. A round bento box.', cue: 'wind', sfx: 'wind bed' },
  path: ['park', ['shop', 'library'], 'curry', 'train', 'rain', 'street', 'home'],
  scenes: [
    { id: 'park', title: 'V3 park', short: 'PARK', bg: 'park', head: 'PARK · 1:00 PM (decisions: hand, errand)',
      why: 'She is eager, then pleased: your hand fits hers, and she says it fits like a lock.',
      beats: [
        { shot: 'match cut in (bento lid → round sun over the park) + stamp', id: 'match', props: { of: 'rooftop', to: 'park' }, stamp: ['PARK', '1:00 PM'], text: 'PARK · 1:00 PM. One hour later. Cherry trees. Petals fall.', cue: 'wind', sfx: 'J-cut: birdsong starts on the rooftop' },
        { shot: 'medium', id: 'park-wide', spk: 'N', text: 'Hold my hand. Hands get lost if you let go.',
          pick: [['Hold it tight', 3, 'hearts', 'A perfect fit. Like a key in a lock.'], ['Hold one finger', 1, 'sweat', 'One finger today. All five later.'], ['Pull your hand back', -4, 'hate', 'Okay. Your hand is cold anyway.']] },
        { shot: 'insert (hands)', id: 'hands-lock', text: 'Close-up. Her fingers lock between yours. Click.', cue: 'thump', sfx: 'click' },
        { shot: 'reaction (you), hold', id: 'reaction', props: { emote: 'sweat' }, text: 'You try to move your fingers. They do not move.', cue: 'silence', sfx: 'SILENCE' },
        { shot: 'two-shot', id: 'ots', spk: 'N', text: 'One job before lunch. My groceries, or my library book?',
          pick: [['Carry her groceries', 2, 'heart', 'Groceries. For our dinner.', { errand: 'groceries' }], ['Return her book', 2, 'heart', 'The book. It is very late.', { errand: 'library' }], ['Do it alone, later', -4, 'hate', 'Alone? No. Groceries. Now.', { errand: 'groceries' }]] },
        { shot: 'match cut out (her hand closes → next object)', id: 'match', props: { of: 'park' }, text: 'exit', cue: 'thump', sfx: 'thump on the cut',
          vary: { errand: { groceries: { text: 'Her hand closes on yours. Cut. Her hand closes on a shop basket.', props: { to: 'shop-street' } }, library: { text: 'Her hand closes on yours. Cut. Her hand closes on a library book.', props: { to: 'rail-crossing' } } } },
          move: ['Walk with her', errandGo] },
      ] },
    { id: 'shop', title: 'V3 shop street', short: 'SHOP', bg: 'shop-street', head: 'SHOP STREET · 2:00 PM (errand: groceries)',
      why: 'She is cheerful, then flat for one line when you count the cups, then cheerful again at once.',
      beats: [
        { shot: 'stamp', id: 'stamp', stamp: ['SHOP STREET', '2:00 PM'], text: 'SHOP STREET · 2:00 PM. Small shops. Pink petals on the roofs.', cue: 'wind', sfx: 'street murmur bed' },
        { shot: 'medium', id: 'shop-street', spk: 'N', text: 'Carrots. Rice. And three cups. We need three cups.' },
        { shot: 'insert (basket)', id: 'three-cups-basket', text: 'Close-up. Three cups. Three round rims, side by side.', cue: 'thump', sfx: 'cups clink' },
        { shot: 'push-in (her face, flat)', id: 'push', spk: 'N', text: 'Do not ask who the third cup is for. Not yet.', cue: 'drone', sfx: 'low drone' },
        { shot: 'cut on action (door)', id: 'shop-exit', text: 'The shop bell rings. You carry the bags out.', cue: 'bell', sfx: 'door bell' },
        { shot: 'match cut out (cup rim → curry plate)', id: 'match', props: { of: 'shop-street', to: 'cafe' }, text: 'Close on one round cup rim. Cut. A round plate of curry.', cue: 'thump', sfx: 'plate down on the cut', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'library', title: 'V3 library', short: 'BOOK', bg: 'rail-crossing', head: 'RAIL CROSSING → LIBRARY · 1:50–2:00 PM (errand: book)',
      why: 'She is scared of the train, then glad when the book is gone: nothing else holds your touch now.',
      beats: [
        { shot: 'stamp', id: 'stamp', stamp: ['RAIL CROSSING', '1:50 PM'], text: 'RAIL CROSSING · 1:50 PM. The bell rings. The gate is down.', cue: 'bell', sfx: 'crossing bell kan-kan' },
        { shot: 'close-up', id: 'crossing-bell', spk: 'N', text: 'A train is a big metal door. I hate doors. Stand closer.', cue: 'train-hum', sfx: 'train passes' },
        { shot: 'match cut (train window → library window) + stamp', id: 'match', props: { of: 'rail-crossing', to: 'library-int' }, stamp: ['LIBRARY', '2:00 PM'], text: 'LIBRARY · 2:00 PM. Ten minutes later. Cool air. Very quiet.', cue: 'silence', sfx: 'train cuts to silence' },
        { shot: 'insert (book slot)', id: 'book-slot', text: 'Close-up. She drops the book in the return slot. Thunk.', cue: 'thump', sfx: 'book thunk' },
        { shot: 'medium', id: 'library-int', spk: 'N', text: 'You touched that book once. So I kept it forty days.' },
        { shot: 'match cut out (square slot → square restaurant window)', id: 'match', props: { of: 'rail-crossing', to: 'cafe' }, text: 'Close on the dark book slot. Cut. A lit restaurant window.', cue: 'thump', sfx: 'thunk becomes a door bell', move: ['Walk to lunch', 'curry'] },
      ] },
    { id: 'curry', title: 'V3 curry house', short: 'CURRY', bg: 'cafe', head: 'CURRY HOUSE · 3:00 PM (decision: lunch)',
      why: 'She is hungry and bossy, then happy because you fed her.',
      beats: [
        { shot: 'stamp', id: 'curry-house-int', stamp: ['CURRY HOUSE', '3:00 PM'], text: 'CURRY HOUSE · 3:00 PM. Small and warm. Two seats, side by side.', cue: 'kettle', sfx: 'restaurant bed + sizzle' },
        { shot: 'medium', id: 'curry-house-int', spk: 'N', text: 'I am hungry. You pick my lunch. Pick the right one.',
          pick: [['Butter chicken for her', 3, 'hearts', 'With naan! You know me.', { food: 'butter' }], ['Katsu curry', 2, 'heart', 'Crunchy. Good choice.', { food: 'katsu' }], ['I am not hungry', -4, 'hate', 'Then you watch me eat.', { food: 'katsu' }]] },
        { shot: 'insert (dish)', id: 'insert', text: 'dish', cue: 'thump', sfx: 'plate down',
          vary: { food: { butter: { text: 'Close-up. Butter chicken. A round plate. Steam from the naan.', props: { shot: 'dish-butter' } }, katsu: { text: 'Close-up. Katsu curry. A round plate. The knife cuts. Crunch.', props: { shot: 'dish-katsu' } } } } },
        { shot: 'two-shot', id: 'ots', spk: 'N', text: 'Feed me first. Then I feed you. That is the rule.' },
        { shot: 'reaction (her, eating)', id: 'nanda-eat-butter', text: 'She eats. She looks at you, not at the food.', cue: 'silence', sfx: 'SILENCE', emo: 'hearts' },
        { shot: 'match cut out (round plate → round station clock)', id: 'match', props: { of: 'cafe', to: 'naan' }, text: 'Close on the empty round plate. Cut. A round clock. 4:30 PM.', cue: 'tick', sfx: 'clock tick on the cut', move: ['Walk to the station', 'train'] },
      ] },
    { id: 'train', title: 'V3 station and train', short: 'TRAIN', bg: 'train', head: 'STATION → TRAIN · 4:30–5:20 PM (loop: the window reflection changes by run)',
      why: 'She is proud and calm. On runs 2 and 3 she is pleased that you notice the repeat.',
      beats: [
        { shot: 'stamp (under the clock)', id: 'station-gate', stamp: ['STATION', '4:30 PM'], text: 'STATION · 4:30 PM. The big clock ticks. She taps her card twice.', cue: 'tick', sfx: 'card beep x2' },
        { shot: 'medium (on the train)', id: 'train', spk: 'N', text: 'Twelve stops to my home. I counted them this morning.', cue: 'train-hum', sfx: 'rail clack bed' },
        { shot: 'insert (your reflection in the window)', id: 'closeup', props: { of: 'train', zoom: 2 }, text: 'loop', vary: { run: { 1: { text: 'In the dark window you see your face. And hers.' }, 2: { text: 'In the window, your face. She says: "Same seat as last time."' }, 3: { text: 'In the window, three of you sit in a row. You, you, you.' } } } },
        { shot: 'stamp (time jump, rain)', id: 'stamp', stamp: ['TRAIN', '5:20 PM'], text: '5:20 PM. Rain on the window. Her stop.', cue: 'rain', sfx: 'rain on glass' },
        { shot: 'match cut out (train doors open → umbrella opens)', id: 'match', props: { of: 'train', to: 'crossing-night' }, text: 'The train doors slide open. Cut. Her umbrella snaps open.', cue: 'thump', sfx: 'door hiss becomes umbrella snap', move: ['Step off the train', 'rain'] },
      ] },
    { id: 'rain', title: 'V3 rain crossing', short: 'RAIN', bg: 'crossing-night', head: 'BIG CROSSING · 5:30 PM, rain (decision: umbrella; the one reality slip)',
      why: 'She is soft and happy under the umbrella. After the signs show her face, she is proud: she wants to be all you see.',
      beats: [
        { shot: 'stamp', id: 'establish', stamp: ['BIG CROSSING', '5:30 PM'], text: 'BIG CROSSING · 5:30 PM. Heavy rain. Big TV signs glow. Nobody else.', cue: 'rain', sfx: 'rain bed' },
        { shot: 'two-shot under umbrella', id: 'crossing-night', spk: 'N', text: 'Share my umbrella. It is small. We have to stand close.',
          pick: [['Step under, close', 4, 'hearts', 'Good. Now the rain cannot take you.'], ['Hold it for her', 1, 'sweat', 'Tall and useful. I am keeping you.'], ['I will just get wet', -4, 'hate', 'Then get wet. Sick boys stay inside.']] },
        { shot: 'REALITY SLIP: pan up, every TV sign shows her face', id: 'push', props: { of: 'crossing-night', to: 1.4 }, text: 'You look up. Every TV sign shows her face. Then the ads come back.', cue: 'static', sfx: 'TV static, 1 s', emo: 'glitch fx' },
        { shot: 'close-up (her, calm)', id: 'closeup', spk: 'N', text: 'You saw me up there. Good. I want to be everything you see.' },
        { shot: 'match cut out (red crossing light → red sunset)', id: 'match', props: { of: 'crossing-night', to: 'street-day' }, text: 'The red walk light. Cut. A red sun over her street. The rain has stopped.', cue: 'silence', sfx: 'rain cuts to silence', move: ['Walk her home', 'street'] },
      ] },
    { id: 'street', title: 'V3 her street', short: 'STREET', bg: 'street-day', head: 'HER STREET · 6:00 → 7:00 PM (decision: pace)',
      why: 'She is scared the day will end. She is calm once the key is in the lock: the day ends at her home.',
      beats: [
        { shot: 'stamp', id: 'stamp', stamp: ['HER STREET', '6:00 PM'], text: 'HER STREET · 6:00 PM. Wet road. Low red sun. She walks slower.', cue: 'wind', sfx: 'cicadas + footsteps' },
        { shot: 'medium', id: 'street-day', spk: 'N', text: 'If we walk slowly, the day cannot end.',
          pick: [['Walk slower with her', 3, 'hearts', 'Slower. Slower. There. We are almost still.'], ['Keep the same pace', 1, 'sweat', 'Same pace. Same day. Same you.'], ['I need to go home', -5, 'hate', 'Home? You are walking me home.']] },
        { shot: 'match cut on the same framing (day → dusk) + stamp', id: 'match', props: { of: 'street-day', to: 'street-dusk' }, bg: 'street-dusk', stamp: ['HER STREET', '7:00 PM'], text: '7:00 PM. Same street, same spot. One hour later. Dark blue sky.', cue: 'silence', sfx: 'SILENCE, then crickets' },
        { shot: 'insert (key)', id: 'key-in-hand', text: 'Close-up. Her house key. She held it all day.', cue: 'tick', sfx: 'keys' },
        { shot: 'close-up', id: 'closeup', bg: 'street-dusk', spk: 'N', text: 'I held it since noon. So I would be ready. For you.' },
        { shot: 'match cut out (key turns → kettle knob turns)', id: 'match', props: { of: 'street-dusk', to: 'teatable' }, bg: 'street-dusk', text: 'The key turns in door 12. Cut. A hand turns the kettle knob.', cue: 'kettle', sfx: 'lock click becomes kettle click', move: ['Follow her inside', 'home'] },
      ] },
    { id: 'home', title: 'V3 her home', short: 'HOME', bg: 'BG-D2', head: 'HER KITCHEN · 7:10 PM',
      why: 'She stops acting like a date. She is at home and in charge.',
      beats: [
        { shot: 'stamp', id: 'kitchen-wide', stamp: ['HER KITCHEN', '7:10 PM'], text: 'HER KITCHEN · 7:10 PM. You wear slippers in your size. Three chairs.', cue: 'kettle', sfx: 'kettle boils' },
        { shot: 'medium', id: 'kitchen-wide', spk: 'N', text: 'Every road today came here. I planned all of them.', emo: 'smile, no blink' },
        { shot: 'insert (pour)', id: 'tea-pour', text: 'Close-up. She pours tea into three round cups.', cue: 'kettle', sfx: 'pour' },
        { shot: 'match cut back (three cups here = three cups at the shop)', id: 'match', props: { of: 'teatable', to: 'shop-street' }, text: 'Cut. The three cups from the shop. The same three. Cut back.', cue: 'thump', sfx: 'cup clink (shop sound)', move: ['Sit down', '!cup'] },
      ] },
  ],
};
